'use client'

import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Download, FileText, Target, Sparkles } from 'lucide-react'
import Layout from '@/components/Layout'
import Card, { CardContent, CardHeader, CardTitle } from '@/components/ui/Card'
import Button from '@/components/ui/Button'

interface Achievement {
  id: string
  title: string
  description: string
  starFormat?: string
  skills: string[]
  quantifiableMetrics?: string
  impact?: string
  isSelected: boolean
}

export default function Resume() {
  const [selectedAchievements, setSelectedAchievements] = useState<Achievement[]>([])
  const [resumeBullets, setResumeBullets] = useState<string[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [isGenerating, setIsGenerating] = useState(false)

  useEffect(() => {
    fetchSelectedAchievements()
  }, [])

  const fetchSelectedAchievements = async () => {
    try {
      setIsLoading(true)
      const response = await fetch('/api/achievements?selected=true')
      const data = await response.json()
      setSelectedAchievements(data.achievements || [])
    } catch (error) {
      console.error('Error fetching selected achievements:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const generateResumeBullets = async () => {
    if (selectedAchievements.length === 0) return

    try {
      setIsGenerating(true)
      // This would integrate with the OpenAI API to generate resume bullets
      // For now, we'll create placeholder bullets based on achievements
      const bullets = selectedAchievements.map(achievement => 
        `• ${achievement.title}: ${achievement.description.substring(0, 120)}${achievement.description.length > 120 ? '...' : ''}`
      )
      setResumeBullets(bullets)
    } catch (error) {
      console.error('Error generating resume bullets:', error)
    } finally {
      setIsGenerating(false)
    }
  }

  const downloadResume = () => {
    // This would generate a PDF resume
    // For now, we'll create a simple text download
    const content = `
RESUME

Selected Achievements:
${resumeBullets.join('\n')}

Generated by Career Journal
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'resume-achievements.txt'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <Layout>
      <div className="space-y-8">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-dark-text">Resume Builder</h1>
            <p className="text-dark-text-muted mt-1">
              Generate ATS-friendly resume content from your selected achievements
            </p>
          </div>
          <div className="flex items-center space-x-4">
            <Button
              onClick={generateResumeBullets}
              disabled={selectedAchievements.length === 0 || isGenerating}
              isLoading={isGenerating}
              className="flex items-center space-x-2"
            >
              <Sparkles className="w-4 h-4" />
              <span>Generate Bullets</span>
            </Button>
            <Button
              variant="secondary"
              onClick={downloadResume}
              disabled={resumeBullets.length === 0}
              className="flex items-center space-x-2"
            >
              <Download className="w-4 h-4" />
              <span>Download</span>
            </Button>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center">
                <Target className="w-8 h-8 text-dark-accent mr-4" />
                <div>
                  <p className="text-sm font-medium text-dark-text-muted">Selected Achievements</p>
                  <p className="text-2xl font-bold text-dark-text">
                    {selectedAchievements.length}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center">
                <FileText className="w-8 h-8 text-dark-success mr-4" />
                <div>
                  <p className="text-sm font-medium text-dark-text-muted">Resume Bullets</p>
                  <p className="text-2xl font-bold text-dark-text">
                    {resumeBullets.length}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center">
                <Sparkles className="w-8 h-8 text-dark-warning mr-4" />
                <div>
                  <p className="text-sm font-medium text-dark-text-muted">Unique Skills</p>
                  <p className="text-2xl font-bold text-dark-text">
                    {Array.from(new Set(selectedAchievements.flatMap(a => a.skills))).length}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Content */}
        <div className="grid lg:grid-cols-2 gap-8">
          {/* Selected Achievements */}
          <Card>
            <CardHeader>
              <CardTitle>Selected Achievements</CardTitle>
            </CardHeader>
            <CardContent>
              {isLoading ? (
                <div className="space-y-3">
                  {[1, 2, 3].map((i) => (
                    <div key={i} className="animate-pulse">
                      <div className="h-4 bg-dark-surface-light rounded w-3/4 mb-2"></div>
                      <div className="h-3 bg-dark-surface-light rounded w-1/2"></div>
                    </div>
                  ))}
                </div>
              ) : selectedAchievements.length > 0 ? (
                <div className="space-y-4">
                  {selectedAchievements.map((achievement, index) => (
                    <motion.div
                      key={achievement.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.3, delay: index * 0.1 }}
                      className="border border-dark-border rounded-lg p-4"
                    >
                      <h4 className="font-medium text-dark-text mb-2">
                        {achievement.title}
                      </h4>
                      <p className="text-sm text-dark-text-muted mb-2">
                        {achievement.description}
                      </p>
                      {achievement.skills.length > 0 && (
                        <div className="flex flex-wrap gap-1">
                          {achievement.skills.map(skill => (
                            <span
                              key={skill}
                              className="px-2 py-1 bg-dark-surface-light text-dark-text text-xs rounded"
                            >
                              {skill}
                            </span>
                          ))}
                        </div>
                      )}
                    </motion.div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8">
                  <Target className="w-12 h-12 text-dark-text-disabled mx-auto mb-4" />
                  <p className="text-dark-text-muted mb-4">
                    No achievements selected for resume
                  </p>
                  <Button onClick={() => window.location.href = '/achievements'}>
                    Select Achievements
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Generated Resume Bullets */}
          <Card>
            <CardHeader>
              <CardTitle>Resume Bullets</CardTitle>
            </CardHeader>
            <CardContent>
              {resumeBullets.length > 0 ? (
                <div className="space-y-3">
                  {resumeBullets.map((bullet, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ duration: 0.3, delay: index * 0.1 }}
                      className="p-3 bg-dark-surface-light rounded-lg text-sm text-dark-text"
                    >
                      {bullet}
                    </motion.div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8">
                  <FileText className="w-12 h-12 text-dark-text-disabled mx-auto mb-4" />
                  <p className="text-dark-text-muted mb-4">
                    {selectedAchievements.length === 0 
                      ? 'Select achievements first'
                      : 'Click "Generate Bullets" to create ATS-friendly resume content'
                    }
                  </p>
                  {selectedAchievements.length > 0 && (
                    <Button 
                      onClick={generateResumeBullets}
                      isLoading={isGenerating}
                    >
                      <Sparkles className="w-4 h-4 mr-2" />
                      Generate Bullets
                    </Button>
                  )}
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Tips */}
        <Card>
          <CardHeader>
            <CardTitle>Resume Tips</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <h4 className="font-medium text-dark-text mb-2">ATS Optimization</h4>
                <ul className="text-sm text-dark-text-muted space-y-1">
                  <li>• Use keywords from the job description</li>
                  <li>• Include quantifiable metrics when possible</li>
                  <li>• Start bullets with strong action verbs</li>
                  <li>• Keep formatting simple and clean</li>
                </ul>
              </div>
              <div>
                <h4 className="font-medium text-dark-text mb-2">Content Best Practices</h4>
                <ul className="text-sm text-dark-text-muted space-y-1">
                  <li>• Focus on impact and results</li>
                  <li>• Use STAR format for detailed examples</li>
                  <li>• Tailor content to target role</li>
                  <li>• Limit to 2-3 bullets per experience</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </Layout>
  )
}